# This is a basic workflow to help you get started with Actions

name: Production Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Laravel Deployment Action
        # You may pin to the exact commit or the version.
        # uses: Pentangle/laravel-deployment-action@a6342bb89f4907d7b1bfd907cd61236ea4088b88
        uses: Pentangle/laravel-deployment-action@v2.1.6
        with:
          # SSH key for deploying, Should be added as a **secret**
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          # IP address of the server being deployed to, Should be added as a **secret**
          SERVER_IP: ${{ secrets.SERVER_IP }}
          # required, used for SSH and deployment path if APP_PATH not specified
          SSH_USER: guest
          # required, used for deployment path if APP_PATH not specified
          APP_NAME: is-seminarska
          # leave blank for 8.0
          PHP_VERSION: 8.1.13
          # version of node to install
          NODE_VERSION: 18.12.1
          # commands to run on server with prefix
          ARTISAN_COMMANDS: | # optional, default is php artisan inspire
            composer dump-autoload
            php artisan inspire
